export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST"
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS"
export const GET_POSTS_FAIL = "GET_POSTS_FAIL"

export const CREATE_POSTS_REQUEST = "CREATE_POSTS_REQUEST"
export const CREATE_POSTS_SUCCESS = "CREATE_POSTS_SUCCESS"
export const CREATE_POSTS_FAIL = "CREATE_POSTS_FAIL"
