export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST"
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS"
export const GET_POSTS_FAIL = "GET_POSTS_FAIL"

export const CREATE_POSTS_REQUEST = "CREATE_POSTS_REQUEST"
export const CREATE_POSTS_SUCCESS = "CREATE_POSTS_SUCCESS"
export const CREATE_POSTS_FAIL = "CREATE_POSTS_FAIL"

export const POST_DELETE_REQUEST = "POST_DELETE_REQUEST"
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS"
export const POST_DELETE_FAIL = "POST_DELETE_FAIL"

export const POST_UPDATE_REQUEST = "POST_UPDATE_REQUEST"
export const POST_UPDATE_SUCCESS = "POST_UPDATE_SUCCESS"
export const POST_UPDATE_FAIL = "POST_UPDATE_FAIL"

export const GET_PAGINATE_REQUEST = "GET_PAGINATE_REQUEST"
export const GET_PAGINATE_SUCCESS = "GET_PAGINATE_SUCCESS"
export const GET_PAGINATE_FAIL = "GET_PAGINATE_FAIL"
